version: "3.9"

services:

  db_backend:
    image: postgres:15.0
    container_name: db_backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - local:/var/lib/postgresql/data

  backend-api:
    container_name: backend-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_backend:5432/marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - '8080:8080'
    depends_on:
      - db_backend

  frontend-client:
    container_name: frontend-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend-api

  pgadmin_backend:
    image: dpage/pgadmin4:2023-03-01-1
    container_name: pgadmin_backend
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: vladik@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - pgadmin_backend:/var/lib/pgadmin

volumes:
  local:
  pgadmin_backend: