version: "3.9"

services:

  backend:
    container_name: backend
    build:

      context: ./backend
      dockerfile: Dockerfile

#    environment:
#
#      SPRING_DATASOURCE_URL: jdbc:postgresql:marketplace//:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

    ports:
      - '8080:8080'

#    depends_on:
#      - db_backend

  frontend:
    container_name: frontend
    build:

      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '5173:5173'